import type { Metadata } from "next";
import "./globals.css";
import Components from "@/components";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`min-h-max font-sans antialiased max-w-screen overflow-x-hidden`}
    >
      <body className="bg-black font-sans min-h-full text-white ">
        <Components>{children}</Components>
      </body>
    </html>
  );
}
